version: '2'

services:
  server:
    build:
      context: server
    volumes:
      - "${PWD}/server:/itmap"
    ports:
      - "0.0.0.0:5000:5000"
    networks:
      - itmap-network
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    # command: ["gunicorn", "--workers=3", "--chdir", "/", "itmap.app:app", "-b", "0.0.0.0:5000"]

  web:
    build: 
      context: web
    volumes:
      - "${PWD}/web/src:/web/src"
      - "${PWD}/web/build:/web/build"
      - "${PWD}/web/package.json:/web/package.json"
    ports:
      - "8020:8020"
    environment:
      HOST: '0.0.0.0'
      PORT: '8020'
      BASE_API: 'http://localhost:5000'
    networks:
      - itmap-network
    command: ["npm", "run", "dev"]

  postgres:
    image: postgres:10
    ports:
      - "127.0.0.1:5437:5432"
    restart: always
    networks:
      - itmap-network

  redis:
    image: redis:4.0
    ports:
      - "127.0.0.1:6378:6379"
    restart: always
    networks:
      - itmap-network

networks:
  itmap-network:
    driver: bridge
