version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes: 
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/itmap-site.conf:/etc/nginx/conf.d/itmap-site.conf"
      - "html:/usr/share/nginx/html"
    networks:
      - itmap-network

  server:
    build:
      context: server
    volumes:
      - "static:/itmap/avatars"
      - "static:/itmap/node_pictures"
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      DB_USER: 'itmap_admin'
      DB_PASSWORD: 'Itmap@678#com'
    networks:
      - itmap-network
    command: ["gunicorn", "--workers=3", "--chdir", "/", "itmap.app:app", "-b", "0.0.0.0:5000"]

  web:
    build: 
      context: web
    volumes:
      - "html:/web/dist"
    command: ["npm", "run", "build"]

  postgres:
    image: postgres:10
    ports:
      - "127.0.0.1:5437:5432"
    volumes:
      - "db:/db/data"
    environment:
      POSTGRES_USER: 'itmap_admin'
      POSTGRES_PASSWORD: 'Itmap@678#com'
      PGDATA: '/db/data'
    restart: always
    networks:
      - itmap-network

  redis:
    image: redis:4.0
    ports:
      - "127.0.0.1:6378:6379"
    restart: always
    networks:
      - itmap-network

networks:
  itmap-network:
    driver: bridge

volumes:
  db:
    driver_opts:
      type: none
      device: /data/db
      o: bind
  html:
    driver_opts:
      type: none
      device: /data/html
      o: bind
  static:
    driver_opts:
      type: none
      device: /data/static
      o: bind
  config:
    driver_opts:
      type: none
      device: /data/config
      o: bind