"""empty message

Revision ID: cd5dc63dc551
Revises: 7cd9872a4fd0
Create Date: 2018-05-03 15:38:32.034928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5dc63dc551'
down_revision = '7cd9872a4fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'description')
    # ### end Alembic commands ###
